---
abstract: 'run parallel task with fork to simple.'
author:
  - 'karupanerura <karupa@cpan.org>'
build_requires:
  IO::Pipe: 0
  Test::More: 0
  Test::Requires: 0
  Test::SharedFork: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.7.4, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parallel-Async
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Parallel::Async:
    file: lib/Parallel/Async.pm
    version: 0.03
  Parallel::Async::Chain:
    file: lib/Parallel/Async/Chain.pm
  Parallel::Async::Task:
    file: lib/Parallel/Async/Task.pm
requires:
  Class::Accessor::Lite: 0
  Time::HiRes: 0
  Try::Tiny: 0
  parent: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/karupanerura/Parallel-Async/issues
  homepage: https://github.com/karupanerura/Parallel-Async
  repository: git://github.com/karupanerura/Parallel-Async.git
version: 0.03
